const githubResult = """{
  "total_count": 29036,
  "incomplete_results": false,
  "items": [
    {
      "login": "jacob",
      "id": 3121,
      "node_id": "MDQ6VXNlcjMxMjE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3121?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacob",
      "html_url": "https://github.com/jacob",
      "followers_url": "https://api.github.com/users/jacob/followers",
      "following_url": "https://api.github.com/users/jacob/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacob/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacob/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacob/subscriptions",
      "organizations_url": "https://api.github.com/users/jacob/orgs",
      "repos_url": "https://api.github.com/users/jacob/repos",
      "events_url": "https://api.github.com/users/jacob/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacob/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobian",
      "id": 21148,
      "node_id": "MDQ6VXNlcjIxMTQ4",
      "avatar_url": "https://avatars1.githubusercontent.com/u/21148?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobian",
      "html_url": "https://github.com/jacobian",
      "followers_url": "https://api.github.com/users/jacobian/followers",
      "following_url": "https://api.github.com/users/jacobian/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobian/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobian/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobian/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobian/orgs",
      "repos_url": "https://api.github.com/users/jacobian/repos",
      "events_url": "https://api.github.com/users/jacobian/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobian/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobandreas",
      "id": 236111,
      "node_id": "MDQ6VXNlcjIzNjExMQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/236111?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobandreas",
      "html_url": "https://github.com/jacobandreas",
      "followers_url": "https://api.github.com/users/jacobandreas/followers",
      "following_url": "https://api.github.com/users/jacobandreas/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobandreas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobandreas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobandreas/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobandreas/orgs",
      "repos_url": "https://api.github.com/users/jacobandreas/repos",
      "events_url": "https://api.github.com/users/jacobandreas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobandreas/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobeisenstein",
      "id": 905244,
      "node_id": "MDQ6VXNlcjkwNTI0NA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/905244?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobeisenstein",
      "html_url": "https://github.com/jacobeisenstein",
      "followers_url": "https://api.github.com/users/jacobeisenstein/followers",
      "following_url": "https://api.github.com/users/jacobeisenstein/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobeisenstein/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobeisenstein/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobeisenstein/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobeisenstein/orgs",
      "repos_url": "https://api.github.com/users/jacobeisenstein/repos",
      "events_url": "https://api.github.com/users/jacobeisenstein/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobeisenstein/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobaraujo7",
      "id": 4047813,
      "node_id": "MDQ6VXNlcjQwNDc4MTM=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4047813?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobaraujo7",
      "html_url": "https://github.com/jacobaraujo7",
      "followers_url": "https://api.github.com/users/jacobaraujo7/followers",
      "following_url": "https://api.github.com/users/jacobaraujo7/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobaraujo7/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobaraujo7/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobaraujo7/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobaraujo7/orgs",
      "repos_url": "https://api.github.com/users/jacobaraujo7/repos",
      "events_url": "https://api.github.com/users/jacobaraujo7/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobaraujo7/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobrosenthal",
      "id": 455796,
      "node_id": "MDQ6VXNlcjQ1NTc5Ng==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/455796?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobrosenthal",
      "html_url": "https://github.com/jacobrosenthal",
      "followers_url": "https://api.github.com/users/jacobrosenthal/followers",
      "following_url": "https://api.github.com/users/jacobrosenthal/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobrosenthal/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobrosenthal/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobrosenthal/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobrosenthal/orgs",
      "repos_url": "https://api.github.com/users/jacobrosenthal/repos",
      "events_url": "https://api.github.com/users/jacobrosenthal/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobrosenthal/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "wangjia55",
      "id": 1639413,
      "node_id": "MDQ6VXNlcjE2Mzk0MTM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1639413?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wangjia55",
      "html_url": "https://github.com/wangjia55",
      "followers_url": "https://api.github.com/users/wangjia55/followers",
      "following_url": "https://api.github.com/users/wangjia55/following{/other_user}",
      "gists_url": "https://api.github.com/users/wangjia55/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wangjia55/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wangjia55/subscriptions",
      "organizations_url": "https://api.github.com/users/wangjia55/orgs",
      "repos_url": "https://api.github.com/users/wangjia55/repos",
      "events_url": "https://api.github.com/users/wangjia55/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wangjia55/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobgil",
      "id": 5342073,
      "node_id": "MDQ6VXNlcjUzNDIwNzM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/5342073?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobgil",
      "html_url": "https://github.com/jacobgil",
      "followers_url": "https://api.github.com/users/jacobgil/followers",
      "following_url": "https://api.github.com/users/jacobgil/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobgil/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobgil/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobgil/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobgil/orgs",
      "repos_url": "https://api.github.com/users/jacobgil/repos",
      "events_url": "https://api.github.com/users/jacobgil/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobgil/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobtomlinson",
      "id": 1610850,
      "node_id": "MDQ6VXNlcjE2MTA4NTA=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1610850?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobtomlinson",
      "html_url": "https://github.com/jacobtomlinson",
      "followers_url": "https://api.github.com/users/jacobtomlinson/followers",
      "following_url": "https://api.github.com/users/jacobtomlinson/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobtomlinson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobtomlinson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobtomlinson/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobtomlinson/orgs",
      "repos_url": "https://api.github.com/users/jacobtomlinson/repos",
      "events_url": "https://api.github.com/users/jacobtomlinson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobtomlinson/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobherrington",
      "id": 11466782,
      "node_id": "MDQ6VXNlcjExNDY2Nzgy",
      "avatar_url": "https://avatars3.githubusercontent.com/u/11466782?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobherrington",
      "html_url": "https://github.com/jacobherrington",
      "followers_url": "https://api.github.com/users/jacobherrington/followers",
      "following_url": "https://api.github.com/users/jacobherrington/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobherrington/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobherrington/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobherrington/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobherrington/orgs",
      "repos_url": "https://api.github.com/users/jacobherrington/repos",
      "events_url": "https://api.github.com/users/jacobherrington/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobherrington/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobbubu",
      "id": 1164378,
      "node_id": "MDQ6VXNlcjExNjQzNzg=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1164378?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobbubu",
      "html_url": "https://github.com/jacobbubu",
      "followers_url": "https://api.github.com/users/jacobbubu/followers",
      "following_url": "https://api.github.com/users/jacobbubu/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobbubu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobbubu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobbubu/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobbubu/orgs",
      "repos_url": "https://api.github.com/users/jacobbubu/repos",
      "events_url": "https://api.github.com/users/jacobbubu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobbubu/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobwilliams",
      "id": 6483379,
      "node_id": "MDQ6VXNlcjY0ODMzNzk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/6483379?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobwilliams",
      "html_url": "https://github.com/jacobwilliams",
      "followers_url": "https://api.github.com/users/jacobwilliams/followers",
      "following_url": "https://api.github.com/users/jacobwilliams/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobwilliams/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobwilliams/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobwilliams/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobwilliams/orgs",
      "repos_url": "https://api.github.com/users/jacobwilliams/repos",
      "events_url": "https://api.github.com/users/jacobwilliams/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobwilliams/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "dekz",
      "id": 27389,
      "node_id": "MDQ6VXNlcjI3Mzg5",
      "avatar_url": "https://avatars0.githubusercontent.com/u/27389?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dekz",
      "html_url": "https://github.com/dekz",
      "followers_url": "https://api.github.com/users/dekz/followers",
      "following_url": "https://api.github.com/users/dekz/following{/other_user}",
      "gists_url": "https://api.github.com/users/dekz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dekz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dekz/subscriptions",
      "organizations_url": "https://api.github.com/users/dekz/orgs",
      "repos_url": "https://api.github.com/users/dekz/repos",
      "events_url": "https://api.github.com/users/dekz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dekz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobwgillespie",
      "id": 130874,
      "node_id": "MDQ6VXNlcjEzMDg3NA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/130874?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobwgillespie",
      "html_url": "https://github.com/jacobwgillespie",
      "followers_url": "https://api.github.com/users/jacobwgillespie/followers",
      "following_url": "https://api.github.com/users/jacobwgillespie/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobwgillespie/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobwgillespie/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobwgillespie/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobwgillespie/orgs",
      "repos_url": "https://api.github.com/users/jacobwgillespie/repos",
      "events_url": "https://api.github.com/users/jacobwgillespie/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobwgillespie/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobstanley",
      "id": 134805,
      "node_id": "MDQ6VXNlcjEzNDgwNQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/134805?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobstanley",
      "html_url": "https://github.com/jacobstanley",
      "followers_url": "https://api.github.com/users/jacobstanley/followers",
      "following_url": "https://api.github.com/users/jacobstanley/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobstanley/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobstanley/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobstanley/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobstanley/orgs",
      "repos_url": "https://api.github.com/users/jacobstanley/repos",
      "events_url": "https://api.github.com/users/jacobstanley/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobstanley/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobsoo",
      "id": 3516693,
      "node_id": "MDQ6VXNlcjM1MTY2OTM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/3516693?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobsoo",
      "html_url": "https://github.com/jacobsoo",
      "followers_url": "https://api.github.com/users/jacobsoo/followers",
      "following_url": "https://api.github.com/users/jacobsoo/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobsoo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobsoo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobsoo/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobsoo/orgs",
      "repos_url": "https://api.github.com/users/jacobsoo/repos",
      "events_url": "https://api.github.com/users/jacobsoo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobsoo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacob-israel-turner",
      "id": 8698364,
      "node_id": "MDQ6VXNlcjg2OTgzNjQ=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/8698364?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacob-israel-turner",
      "html_url": "https://github.com/jacob-israel-turner",
      "followers_url": "https://api.github.com/users/jacob-israel-turner/followers",
      "following_url": "https://api.github.com/users/jacob-israel-turner/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacob-israel-turner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacob-israel-turner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacob-israel-turner/subscriptions",
      "organizations_url": "https://api.github.com/users/jacob-israel-turner/orgs",
      "repos_url": "https://api.github.com/users/jacob-israel-turner/repos",
      "events_url": "https://api.github.com/users/jacob-israel-turner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacob-israel-turner/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobkahn",
      "id": 7871817,
      "node_id": "MDQ6VXNlcjc4NzE4MTc=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/7871817?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobkahn",
      "html_url": "https://github.com/jacobkahn",
      "followers_url": "https://api.github.com/users/jacobkahn/followers",
      "following_url": "https://api.github.com/users/jacobkahn/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobkahn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobkahn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobkahn/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobkahn/orgs",
      "repos_url": "https://api.github.com/users/jacobkahn/repos",
      "events_url": "https://api.github.com/users/jacobkahn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobkahn/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JacobBennett",
      "id": 1517011,
      "node_id": "MDQ6VXNlcjE1MTcwMTE=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1517011?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JacobBennett",
      "html_url": "https://github.com/JacobBennett",
      "followers_url": "https://api.github.com/users/JacobBennett/followers",
      "following_url": "https://api.github.com/users/JacobBennett/following{/other_user}",
      "gists_url": "https://api.github.com/users/JacobBennett/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JacobBennett/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JacobBennett/subscriptions",
      "organizations_url": "https://api.github.com/users/JacobBennett/orgs",
      "repos_url": "https://api.github.com/users/JacobBennett/repos",
      "events_url": "https://api.github.com/users/JacobBennett/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JacobBennett/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobrask",
      "id": 58563,
      "node_id": "MDQ6VXNlcjU4NTYz",
      "avatar_url": "https://avatars2.githubusercontent.com/u/58563?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobrask",
      "html_url": "https://github.com/jacobrask",
      "followers_url": "https://api.github.com/users/jacobrask/followers",
      "following_url": "https://api.github.com/users/jacobrask/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobrask/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobrask/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobrask/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobrask/orgs",
      "repos_url": "https://api.github.com/users/jacobrask/repos",
      "events_url": "https://api.github.com/users/jacobrask/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobrask/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobh",
      "id": 409333,
      "node_id": "MDQ6VXNlcjQwOTMzMw==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/409333?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobh",
      "html_url": "https://github.com/jacobh",
      "followers_url": "https://api.github.com/users/jacobh/followers",
      "following_url": "https://api.github.com/users/jacobh/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobh/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobh/orgs",
      "repos_url": "https://api.github.com/users/jacobh/repos",
      "events_url": "https://api.github.com/users/jacobh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobh/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobbednarz",
      "id": 283234,
      "node_id": "MDQ6VXNlcjI4MzIzNA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/283234?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobbednarz",
      "html_url": "https://github.com/jacobbednarz",
      "followers_url": "https://api.github.com/users/jacobbednarz/followers",
      "following_url": "https://api.github.com/users/jacobbednarz/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobbednarz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobbednarz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobbednarz/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobbednarz/orgs",
      "repos_url": "https://api.github.com/users/jacobbednarz/repos",
      "events_url": "https://api.github.com/users/jacobbednarz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobbednarz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobsalmela",
      "id": 3843505,
      "node_id": "MDQ6VXNlcjM4NDM1MDU=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3843505?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobsalmela",
      "html_url": "https://github.com/jacobsalmela",
      "followers_url": "https://api.github.com/users/jacobsalmela/followers",
      "following_url": "https://api.github.com/users/jacobsalmela/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobsalmela/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobsalmela/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobsalmela/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobsalmela/orgs",
      "repos_url": "https://api.github.com/users/jacobsalmela/repos",
      "events_url": "https://api.github.com/users/jacobsalmela/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobsalmela/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacoborus",
      "id": 829859,
      "node_id": "MDQ6VXNlcjgyOTg1OQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/829859?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacoborus",
      "html_url": "https://github.com/jacoborus",
      "followers_url": "https://api.github.com/users/jacoborus/followers",
      "following_url": "https://api.github.com/users/jacoborus/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacoborus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacoborus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacoborus/subscriptions",
      "organizations_url": "https://api.github.com/users/jacoborus/orgs",
      "repos_url": "https://api.github.com/users/jacoborus/repos",
      "events_url": "https://api.github.com/users/jacoborus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacoborus/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobdufault",
      "id": 356714,
      "node_id": "MDQ6VXNlcjM1NjcxNA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/356714?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobdufault",
      "html_url": "https://github.com/jacobdufault",
      "followers_url": "https://api.github.com/users/jacobdufault/followers",
      "following_url": "https://api.github.com/users/jacobdufault/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobdufault/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobdufault/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobdufault/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobdufault/orgs",
      "repos_url": "https://api.github.com/users/jacobdufault/repos",
      "events_url": "https://api.github.com/users/jacobdufault/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobdufault/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jacobmischka",
      "id": 3939997,
      "node_id": "MDQ6VXNlcjM5Mzk5OTc=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3939997?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jacobmischka",
      "html_url": "https://github.com/jacobmischka",
      "followers_url": "https://api.github.com/users/jacobmischka/followers",
      "following_url": "https://api.github.com/users/jacobmischka/following{/other_user}",
      "gists_url": "https://api.github.com/users/jacobmischka/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jacobmischka/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jacobmischka/subscriptions",
      "organizations_url": "https://api.github.com/users/jacobmischka/orgs",
      "repos_url": "https://api.github.com/users/jacobmischka/repos",
      "events_url": "https://api.github.com/users/jacobmischka/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jacobmischka/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "fat",
      "id": 169705,
      "node_id": "MDQ6VXNlcjE2OTcwNQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/169705?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fat",
      "html_url": "https://github.com/fat",
      "followers_url": "https://api.github.com/users/fat/followers",
      "following_url": "https://api.github.com/users/fat/following{/other_user}",
      "gists_url": "https://api.github.com/users/fat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fat/subscriptions",
      "organizations_url": "https://api.github.com/users/fat/orgs",
      "repos_url": "https://api.github.com/users/fat/repos",
      "events_url": "https://api.github.com/users/fat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fat/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Greenwolf",
      "id": 48361984,
      "node_id": "MDQ6VXNlcjQ4MzYxOTg0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/48361984?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Greenwolf",
      "html_url": "https://github.com/Greenwolf",
      "followers_url": "https://api.github.com/users/Greenwolf/followers",
      "following_url": "https://api.github.com/users/Greenwolf/following{/other_user}",
      "gists_url": "https://api.github.com/users/Greenwolf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Greenwolf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Greenwolf/subscriptions",
      "organizations_url": "https://api.github.com/users/Greenwolf/orgs",
      "repos_url": "https://api.github.com/users/Greenwolf/repos",
      "events_url": "https://api.github.com/users/Greenwolf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Greenwolf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JacobLett",
      "id": 8182890,
      "node_id": "MDQ6VXNlcjgxODI4OTA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8182890?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JacobLett",
      "html_url": "https://github.com/JacobLett",
      "followers_url": "https://api.github.com/users/JacobLett/followers",
      "following_url": "https://api.github.com/users/JacobLett/following{/other_user}",
      "gists_url": "https://api.github.com/users/JacobLett/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JacobLett/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JacobLett/subscriptions",
      "organizations_url": "https://api.github.com/users/JacobLett/orgs",
      "repos_url": "https://api.github.com/users/JacobLett/repos",
      "events_url": "https://api.github.com/users/JacobLett/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JacobLett/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ioerror",
      "id": 145203,
      "node_id": "MDQ6VXNlcjE0NTIwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/145203?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ioerror",
      "html_url": "https://github.com/ioerror",
      "followers_url": "https://api.github.com/users/ioerror/followers",
      "following_url": "https://api.github.com/users/ioerror/following{/other_user}",
      "gists_url": "https://api.github.com/users/ioerror/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ioerror/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ioerror/subscriptions",
      "organizations_url": "https://api.github.com/users/ioerror/orgs",
      "repos_url": "https://api.github.com/users/ioerror/repos",
      "events_url": "https://api.github.com/users/ioerror/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ioerror/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}""";